### ISSUE TITLE
Download only the required artifact

### ISSUE THREAD

**Issue by glenthomas** [cloudposse/github-action-matrix-outputs-read#29]
## Describe the Feature

My workflow is uploading other artifacts. This action downloads all of them. Could it only download a single, named artifact instead?

## Expected Behavior

The github-action-matrix-outputs-read action does not download all artifacts from the workflow run, it only downloads a named artifact based on the `matrix-step-name` input.

## Use Case

My workflow uploads a lot of chunky artifacts that I don't want to be downloaded again for this action.

## Describe Ideal Solution

The github-action-matrix-outputs-read action does not download all artifacts from the workflow run, it only downloads a named artifact based on the `matrix-step-name` input.

## Alternatives Considered

🤷‍♂️

**Comment by cleverer** [comment]
We have an issue that is tangential to this:

The [latest update](https://github.com/docker/build-push-action/releases/tag/v6.0.0) of `docker/build-push-action` now creates artifacts as well. `cloudposse/github-action-matrix-outputs-read` downloads those as well, but fails when it tries to extract them… which breaks our CI pipeline.

Fortunately, we have no need for those docker artifacts and just disabled it, but I think this could be a common issue when using this action.

For reference, the error message we had was like this:
```
Error: Unable to download artifact(s): Unable to download and extract artifact: Artifact download failed after 5 retries.
/home/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2478
            throw new Error(`Unable to download and extract artifact: ${error.message}`);
                  ^

Error: Unable to download and extract artifact: Artifact download failed after 5 retries.
    at /home/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2478:19
    at Generator.throw (<anonymous>)
    at rejected (/home/runner/work/_actions/actions/download-artifact/v4/dist/index.js:2320:65)

Node.js v20.13.1
```

Some related info can also be found here:
- https://github.com/IntersectMBO/cardano-ledger/pull/4424
- https://github.com/actions/download-artifact/issues/328

**Comment by intel352** [comment]
I'm also impacted by this issue, I'm surprised this is being left as-is. They tout the new artifact behavior as more performant, but I can't see how downloading unrelated artifacts are anywhere near relevant or performant for the action.

**Comment by intel352** [comment]
I've forked the write and read actions, and adapted both to support a filterable file naming scheme for the artifacts, so that all artifacts are no longer downloaded.

https://github.com/marketplace/actions/matrix-outputs-write-filtered
https://github.com/marketplace/actions/matrix-outputs-read-filtered

**Comment by andrey-petrenko-develeap** [comment]
@intel352 you're the lifesaver, thank you!
It's weird that one-line fix like that still hasn't been applied yet.
